[package]
name = "songrec"
license = "GPL-3.0+"
description = "An open-source Shazam client for Linux, written in Rust."
homepage = "https://github.com/marin-m/SongRec"
repository = "https://github.com/marin-m/SongRec"
readme = "README.md"
keywords = ["shazam", "audio", "audio-fingerprinting"]
categories = ["multimedia::audio", "command-line-utilities"]
version = "0.1.6"
authors = ["marin-m"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chfft = "0.3.4" # Fast Fourier transform
byteorder = "1.3.4" # Used for reading and writing binary structures
crc32fast = "1.2.0" # Used for the CRC-32 checksum in the binary signature
base64 = "0.12.3"
reqwest = { version = "0.10.7", features = ["blocking", "json"] }
rodio = "0.13.1" # For reading WAV/MP3/FLAG/OGG files, resampling and playing audio.
clap = "2.33.2" # For argument parsing
cpal = "0.13.3" # For recording audio
gtk = { version = "0.9.2", features = ["v3_16", "v3_20", "v3_22"] } # For the GUI
gdk = "0.13.2"
gio = "0.9.1"
hound = "3.4.0" # For writing WAV files
serde_json = "1.0.57" # For decoding and encoding JSON
uuid = { version = "0.8.1", features = ["v4"] }
glib = "0.10.3"
percent-encoding = "2.1.0" # For percent-encoding contents in URLs
serde = { version = "1.0.115", features = ["derive"] }
csv = "1.1.3"
chrono = "0.4.13" # For formatting dates
app_dirs = "1.2.1" # For obtaining and creating either the %APPDATA%, the dotfile path or similar
rand = "0.7.3"
tempfile = "3.2.0"
gdk-pixbuf = "0.9.0"

[target.'cfg(target_os = "linux")'.dependencies]
gag = "0.1.10" # Crate to silence stderr when CPAL produces uncontrolled AlsaLib output

